### ISSUE TITLE
pronunciation of mobile

### ISSUE THREAD

**Issue by rnons** [shimohq/chinese-programmer-wrong-pronunciation#1]
http://dictionary.cambridge.org/dictionary/english/mobile

also, please add `safari`

**Comment by wanming** [comment]
`mobile` has been removed.
What's the wrong pronunciation of `safari`?

**Comment by rnons** [comment]
I've often heard people pronounce `safari` as `sæfəri` :D

**Comment by wanming** [comment]
:)
