### ISSUE TITLE
加一个data

### ISSUE THREAD

**Issue by songzhw** [shimohq/chinese-programmer-wrong-pronunciation#10]
以前都发 date的音
后来才知道错了， 要发 类似于"de ta"的音

**Comment by myst729** [comment]
app as **['eɪ'pi:'pi:]**
digest as **['digɛst]**
canary as **['kænəri]**
typical as **['taɪpɪkəl]**
access as **[ək'sɛs]**

**Comment by wanming** [comment]
@songzhw 看了下 date 的音对于英式发音来说的话基本正确.

@myst729 加了 `app`, `digest`, `typical`, `access`, canary 不常用没加. 谢谢

**Comment by songzhw** [comment]
@myst729 , @wanming ,  感觉 @myst729 的音不对??
typical 的前面应该发: tipi
app也是发 [æp]吧， 是application的简称
digest也应该发['dɑɪdʒɛst] ， 前面是[ɑɪ]

**Comment by myst729** [comment]
@songzhw 我列的都是错误的读音……
