### ISSUE TITLE
daemon 的发音

### ISSUE THREAD

**Issue by GhostComputing** [shimohq/chinese-programmer-wrong-pronunciation#108]
daemon | BrE ˈdiːmən, AmE ˈdimən |

后台守候进程。很多人发音经常变成 |dɛmən| ，而且这个词很容易拼写错误变成 demon | BrE ˈdiːmən, AmE ˈdimən | ，二者同音异义，后者是魔鬼的意思。

英文世界中有过这样的讨论：[what-is-the-difference-between-daemon-and-demon-in-a-religious-context](http://english.stackexchange.com/questions/39266/what-is-the-difference-between-daemon-and-demon-in-a-religious-context)。从词源溯义，二者应该同宗，但是前者是代表："supernatural beings between mortals and gods, such as inferior divinities and ghosts of dead heroes"，后者是 "solely a bad spirit"。

所以，绝大多数情况下，后台守候进程（daemon）都是好的，但是稍微不注意，就会变成魔鬼（demon）。

**Comment by wanming** [comment]
写个 PR 吧~

**Comment by yjfvictor** [comment]
这个其实是英语历史拼写问题，比如“百科全书”可以拼写成encyclop**ae**dia或者encyclop**e**dia，“恋童”可以拼写成p**ae**dophilia或者p**e**dophilia，“哲学”可以拼写成。这个是其实是拉丁文转写的遗留问题。拉丁文有个字母 æ ，转写成英文的时候，有人写成 ae ，有人写成 e 。
