### ISSUE TITLE
JSON ???

### ISSUE THREAD

**Issue by seasonyuu** [shimohq/chinese-programmer-wrong-pronunciation#109]

**Comment by seasonyuu** [comment]
我想肯定不是 /dʒeisn/

**Comment by lilydjwg** [comment]
@seasonyuu [How do you pronounce "JSON"? on Quora](https://www.quora.com/How-do-you-pronounce-JSON/answer/Yad-Faeq?srid=uP82Y)

**Comment by seasonyuu** [comment]
@lilydjwg I am not sure.Any idea?

**Comment by XavierSAndroid** [comment]
Jay-Son maybe

**Comment by seasonyuu** [comment]
@XavierSAndroid yep, maybe. I found it may be "/dʒsʌn/" or "/dʒeisʌn/"  somewhere

**Comment by wanming** [comment]
参考谍影重重~

**Comment by seasonyuu** [comment]
@wanming 怎么说？？我没看过。。。。

**Comment by yjfvictor** [comment]
/ˈdʒeɪsən/  或  /dʒeɪˈsɒn/
