### ISSUE TITLE
Linux 发音不对

### ISSUE THREAD

**Issue by lushl9301** [shimohq/chinese-programmer-wrong-pronunciation#115]
According to wikipedia https://en.wikipedia.org/wiki/Linux

> Linux (pronounced /ˈlɪnəks/ lin-əks[9][10] or, less frequently, /ˈlaɪnəks/ lyn-əks)

您用的发音按钮，发出的是后者的音，而标注发音是前者。前者较为常用。https://upload.wikimedia.org/wikipedia/commons/0/03/Linus-linux.ogg

**Comment by tlze** [comment]
支持，我也经常听到的是
http://dict.youdao.com/dictvoice?audio=linux&type=2

**Comment by heyz-lzj** [comment]
标注的是对的 发音的是错的

**Comment by kaktos** [comment]
发音都是引的英音吧。。能改成美音吗..

**Comment by wanming** [comment]
@kaktos 之前是用的美式的，但是考虑到大部分人高中大学学的音标是英式的就统一用英式的了。
发音改过来了

**Comment by yjfvictor** [comment]
@kaktos 

这个不是英音美音的问题，这是瑞典音。Linus Torvalds 是瑞典人，他用瑞典音把 Linux 读成 /ˈlɪnəks/。

https://en.wikipedia.org/wiki/File:Linus-linux.ogg
