### ISSUE TITLE
【补充】SQL

### ISSUE THREAD

**Issue by peterchinzhen** [shimohq/chinese-programmer-wrong-pronunciation#120]
| 单词  | 正确发音 | 错误发音 |
| ---- | ------- | ------- |
| SQL [🔊](http://dict.youdao.com/dictvoice?audio=SQL) | ✅ [ˈɛs kjuː ˈɛl] or [ˈsiːkwəl] | ❌ [sək(ə)l] |

参考于 https://en.wikipedia.org/wiki/SQL

**Comment by yw981** [comment]
+1
