### ISSUE TITLE
GUI本身就是缩写吧 为何要强行发音

### ISSUE THREAD

**Issue by CepheiSigma** [shimohq/chinese-programmer-wrong-pronunciation#131]
Graphical user interface
https://en.wikipedia.org/w/index.php?title=GUI&redirect=no

**Comment by wsslsy** [comment]
这个逻辑不成立吧。AJAX这种术语也是缩写，但是大家读起来都会说['eidʒæks]。这个项目说的就是习惯问题。如果国外开发者也将GUI分开读，这才应该是“不要强行发音”正确原因吧。

**Comment by lhmouse** [comment]
无知。

**Comment by gitzxon** [comment]
外国人怎么读你就怎么读呗，不需要较真。

**Comment by CepheiSigma** [comment]
@lhmouse 反驳请带上依据，谢谢

**Comment by CepheiSigma** [comment]
词典上确实有GUI这个词也有发音

**Comment by lhmouse** [comment]
@CepheiSigma 随便 stfw 一下都一大把资料的东西为什么要我提供依据。懒惰不是无知的藉口。 <https://en.m.wiktionary.org/wiki/GUI>

**Comment by CepheiSigma** [comment]
@lhmouse 那请你指出来啊 难道你只会喷人？

**Comment by lhmouse** [comment]
@CepheiSigma 我只是指出你在发表观点之前没有 stfw 的事实，怎么就成“喷人”了。真滑稽。

**Comment by CepheiSigma** [comment]
第一这并不是观点，我只就发音这个问题进行了请教，其他人都对问题进行了回答只有你，既没有指点问题本身，也没有对问题进行讨论，我真不知道你所为何意 @lhmouse

**Comment by lhmouse** [comment]
@CepheiSigma

> 第一这并不是观点，我只就发音这个问题进行了请教，
何谓 _请教_？“为何要强行发音”叫 _请教_？

> 其他人都对问题进行了回答
谁 _回答_ 了？ GUI 这个词怎么读完全就是个自然语言 hardcoding 有什么好回答的。去查词典啊，去问谷狗啊。

> 只有你，既没有指点问题本身，也没有对问题进行讨论，我真不知道你所为何意 @lhmouse
这只是针对 _你_ 的那个自以为是的标题而已。 You are ignorance. The fact is as simple as that, period.

**Comment by CepheiSigma** [comment]
@lhmouse 
第一我是用的为何 
第二@wssly 也指出了也回答了AJAX，GUI的读音
第三第一次见到在GitHub上不对回答对人的，看来你怕不是来挑起争端的

**Comment by lhmouse** [comment]
@CepheiSigma 
如果你是在认认真真地提问，希望你下次能把”强行“这种字眼去掉。它带有不满的情感色彩，也很刺眼。

> [17:59:06] <varna> “AJAX这种术语也是缩写” --> Ajax这个词是个双关
> [17:59:16] * ChanServ gives voice to varna
> [18:02:53] <lh_mouse> Ajax /ˈeɪdʒæks/ 
> [18:02:53] <lh_mouse> N the son of Telamon; a Greek hero of the Trojan War who killed himself in vexation when Achilles' armour was given to Odysseus 埃阿斯; 特洛伊战争中的希腊英雄，忒拉蒙之子
> [18:03:53] <varna> 是的

**Comment by CepheiSigma** [comment]
@lhmouse 这个可能是对于用词习惯和理解的不同，我以后会注意的，其次感谢你的解答。

**Comment by lhmouse** [comment]
:joy: :joy: :joy:

**Comment by CepheiSigma** [comment]
忘了，同时也感谢以上进行解答的朋友

**Comment by yjfvictor** [comment]
请楼主改变习惯。绝大多数缩写词都是当作一个单词来读，很少一个一个字母读的。

比如说，联合国教科文组织UNESCO，就读/juːˈneskəʊ/；联合国儿童基金会UNICEF，就是读  /ˈjuːnɪsef/，不明飞行物 UFO，就是读 /ˈjuːfəʊ/。

缩写词当作一个单词来读，这是惯例。只有那种实在读不来的，比如USA，那才会读字母。
