### ISSUE TITLE
希望添加各大IDE的读音

### ISSUE THREAD

**Issue by whwq2012** [shimohq/chinese-programmer-wrong-pronunciation#135]
程序员打交道最多的还是IDE吧，这个读错的概率很大啊，希望增加这些IDE的读音

**Comment by lilydjwg** [comment]
这个很难么？举点有意思的例子呀。我想了一下，PyCharm？WebStorm？Sublime Text？Idea？Eclipse？基本上都是很正常的英语单词呀。

**Comment by hanxu317317** [comment]
其实有一个很神奇的地方....ide这玩意无论什么发音.大家都是懂的~~

**Comment by whwq2012** [comment]
@lilydjwg 读错会很尴尬啊，特别是遇上那些挑毛病的人。比如pycharm，我喜欢读成p-y-charm，但是正确的读音好像是pai-charm。intellij甚至是都不会读。
@hanxu317317 但是因为每个人读得可能不同，要理解别人说的，要反应一会儿才知道

**Comment by lilydjwg** [comment]
@whwq2012 你为什么要把 py 分开读，又不会有歧义。intellij 正式写作 IntelliJ，应该是读 [ɪnˌtelɪ ˈdʒei] 了。 不过 IntelliJ IDEA 一起的话可能会发生连读。随意 Google 一下可以确认： http://www.pronouncekiwi.com/IntelliJ%20IDEA

**Comment by lilydjwg** [comment]
@hanxu317317 发音和我所以为的不一样我是不会很快理解的。这也是为什么大家需要统一找一个正确的读音的原因。

**Comment by wanming** [comment]
有趣的提议。建议针对到某个单词而不是某一类词。

**Comment by whwq2012** [comment]
@lilydjwg  因为我是按照直觉读的，因为直觉不可信，所以才来寻求帮助啊

**Comment by wanming** [comment]
feel free to reopen
