### ISSUE TITLE
吐槽这个正确或者错误读音的说法

### ISSUE THREAD

**Issue by LovePluto** [shimohq/chinese-programmer-wrong-pronunciation#138]
像APP这种本来就不是按照单词读音来拼读的，本来就是按照单词组合APP来读的，为什么要强制说发音错误，并且一定要按照拼写来读？

**Comment by hkongm** [comment]
书本正确 or 习惯正确？

俺读 艾普

**Comment by LovePluto** [comment]
@hkongm 你这书本正确的结论是哪里出来的啊，APP本来是Application的简写的，简写你要按照发音读也说不过去啊，文章作者说的参考了有道，但是APP在有道上面也是两个发音的，一个 阿普 读音，一个APP单词组合读音的

**Comment by LovePluto** [comment]
我并不是完全的否认作者的努力，作者有些单词拼写纠正还是很值得鼓励的，只是觉得有些本来是单词简写，比如App，GUI这种，强行说发音，总觉得没有必要的，就像我标题一样，我知识吐槽一下的

**Comment by lilydjwg** [comment]
发音不统一有两个方面的问题：

1. 你说，别人听不懂
2. 别人说，你听不懂

虽然像 app 这种，你直接拼出来，别人疑惑一下也能明白，但总归是影响交流的顺畅的。
