### ISSUE TITLE
宽式音标只能以斜线标注，不得以方括号标注

### ISSUE THREAD

**Issue by lhmouse** [shimohq/chinese-programmer-wrong-pronunciation#153]
目前页面上的音标都是宽式音标，只能以 // 标注。

Reference: <https://en.wikipedia.org/wiki/Phonetic_transcription#Narrow_versus_broad_transcription>

**Comment by lilydjwg** [comment]
是啊，所以[我的版本](https://github.com/lilydjwg/chinese-programmers-correct-pronunciations-handbook)早改了。

**Comment by lhmouse** [comment]
你们 OS community 这个 efficiency 啊……

**Comment by b1f6c1c4** [comment]
Duplicate of #99. Solved by #290.

**Comment by lhmouse** [comment]
ok.
