### ISSUE TITLE
Python ==>  ['paɪθɑn]  (常被读为 拍审)

### ISSUE THREAD

**Issue by ssthouse** [shimohq/chinese-programmer-wrong-pronunciation#159]

**Comment by lilydjwg** [comment]
难道不对么？

**Comment by ssthouse** [comment]
@lilydjwg  应该读  `拍赏`

**Comment by lilydjwg** [comment]
能不能用国际音标……

有道和 Dictionary.com 说两种读法（/θən/ /θɒn/）都是可以的。

**Comment by plestoon** [comment]
/θən/作为英音没什么可说的，/θɒn/大家注意美语里短音ɒ和ʌ发音非常接近。至于音标写法，统一就好，像老美用的韦氏更适合他们自己 ，例如\ ˈpī-ˌthän , -thən \，仔细看，ä体现了其发音更倾向于a，而非o。

**Comment by lilydjwg** [comment]
ɒ 和 ʌ 不接近啊。ɒ 是 ɑ 的圆唇音，不过很多时候感觉很多美国人发音的时候并没有圆唇（比如 hot），以至于牛津开始用 ɑ 来标记了。ɔ 这个音现在的词典已经不用了。

我倒是不希望一般词典的标音过分纠结到底读的哪个音素。因为只要音位没差，都容易懂，而鉴于如此多的奇葩发音，我觉得还是降低要求，先让大家说的都能听懂，再去追求标准规范不带母语口音吧。

**Comment by yjfvictor** [comment]
https://www.oxfordlearnersdictionaries.com/definition/english/python
