### ISSUE TITLE
英美发音区别特别大，最好把两种发音都注明

### ISSUE THREAD

**Issue by plestoon** [shimohq/chinese-programmer-wrong-pronunciation#174]
注意，我们从小被教的是连老师都分不清的英音，平时接触的又是美音较多。所以国内英语发音现象特别混乱。

细心的同学大概在一些字典里已经注意到了这个区别，但大部分人基本都是随机的选一种记下。

这在交流的时候是非常尴尬的，一会英音，一会美音，一会儿话音。老外听了会有一种“你英语是谁教的？”感觉。

除了发音，还有口音，这个没在国外呆过的基本掌握不了，也没法掌握。电影里的口音你根本就不知道是哪的，最多能听出个英国的还是美国的，再强一点能听出美国西部的。

另外还有拼写上的不同，例如center/centre。用词不同petrol/gas。

回到本话题，现在只标了英音，有些随机了美音的同学会认为你标的不对。

还有一些词，很多在国际上都是没有固定标准发音的，比较常见的Ubuntu和Youtube，发音都不是唯一的。我之前一个老外同事，他说他都不知道Ubuntu的正确发音是什么，就是选了一个他认为读起来舒服的。

**Comment by lilydjwg** [comment]
很多时候我都不知道自己听到的口音是哪里的。目前我能分辨出来的是美国、英国、中国、部分欧洲口音（印度口音遇到了大概能分辨出来，不过很难遇到）。再细了都查不到了。

我觉得要不只标美音算了，别难为那些连很常见的词都说得让人不知所云的人了。

**Comment by DragonQuestHero** [comment]
同意不能再多...
同理还有Uber

**Comment by jnoodle** [comment]
建议都按照美音来发：https://github.com/jnoodle/common-programming-words-english-pronunciation

**Comment by wanming** [comment]
美音已加，感谢建议
