### ISSUE TITLE
resort 是不是不应该出现在这个表格里？

### ISSUE THREAD

**Issue by zouzhiheng** [shimohq/chinese-programmer-wrong-pronunciation#183]
google 翻译了一下，英文 "resort " 的意思是采取、度假胜地、娱乐场、玩弄等意思，如果是这个意思的话，表格里的读音是正确的。但对程序员而言，resort 这个单词一般特指 re + sort，即重排序，这个时候 [rɪˈsɔ:t] 的读音应该是正确的，我在 google 翻译里打 "re sort"，出来的读音也和  [rɪˈsɔ:t] 一样。

所以，resort 是不是不应该出现在这个表格里？或许作者加个注释，说明一下 resort 这个单词的意义会比较好。

**Comment by lilydjwg** [comment]
re-sort? 没见过，除了变量名里。

resort 这个词还是挺常用的啊。比如「Thus X can't be used in this case so we have to resort to a more complicated way to...」。
