### ISSUE TITLE
SHA1 SHA256 一般都会读错

### ISSUE THREAD

**Issue by isLishude** [shimohq/chinese-programmer-wrong-pronunciation#187]
国外的视频一般分开读 S-H-A 1，国内大部分都是读作 “沙万”，还有更不准确的叫法 “哈希一”，这就算读错了吧。。还有 SHA256，但我遇到的很多读错的直接就 “沙二五六”或者“哈希二五六”。

我觉得有必要添加这个，不过词典没有这个词，不好标音标。

**Comment by lilydjwg** [comment]
为什么不读「沙一」要读「沙万」呢……

**Comment by jingzhou123** [comment]
感觉傻大，傻256才是符合我国现阶段发展规律的

**Comment by isLishude** [comment]
> 为什么不读「沙一」要读「沙万」呢……

有的人会这样说，这个词在国内千奇百怪的读法。往往对方说完，自己得黑人问号脸几秒 😄

**Comment by vivianQizhu** [comment]
我们国外同事都是读“沙万” 有些视频分开读也不代表合起来读就不对。
