### ISSUE TITLE
鸿鹄之志

### ISSUE THREAD

**Issue by wrb233** [shimohq/chinese-programmer-wrong-pronunciation#199]

**Comment by wanming** [comment]
鸿浩之志

**Comment by wrb233** [comment]
i'm sorry, it's just a joke


------------------ 原始邮件 ------------------
发件人: "yifan111"<notifications@github.com>;
发送时间: 2018年5月14日(星期一) 下午2:23
收件人: "shimohq/chinese-programmer-wrong-pronunciation"<chinese-programmer-wrong-pronunciation@noreply.github.com>;
抄送: "浪子回头"<982440462@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shimohq/chinese-programmer-wrong-pronunciation] 鸿鹄之志 (#199)



wHAT? 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "TomWan"<notifications@github.com>; 
 发送时间: 2018年5月14日(星期一) 中午1:48 
 收件人: "shimohq/chinese-programmer-wrong-pronunciation"<chinese-programmer-wrong-pronunciation@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>;  
 主题: Re: [shimohq/chinese-programmer-wrong-pronunciation] 鸿鹄之志 (#199) 
 
 
 
 
 鸿浩之志

**Comment by YIFAN1111** [comment]
You fooled me




------------------ 原始邮件 ------------------
发件人: "主要是懒"<notifications@github.com>;
发送时间: 2018年5月14日(星期一) 下午2:25
收件人: "shimohq/chinese-programmer-wrong-pronunciation"<chinese-programmer-wrong-pronunciation@noreply.github.com>;
抄送: "逸帆"<1309672328@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [shimohq/chinese-programmer-wrong-pronunciation] 鸿鹄之志 (#199)



i'm sorry, it's just a joke 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "yifan111"<notifications@github.com>; 
 发送时间: 2018年5月14日(星期一) 下午2:23 
 收件人: "shimohq/chinese-programmer-wrong-pronunciation"<chinese-programmer-wrong-pronunciation@noreply.github.com>; 
 抄送: "浪子回头"<982440462@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [shimohq/chinese-programmer-wrong-pronunciation] 鸿鹄之志 (#199) 
 
 
 
 wHAT?  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "TomWan"<notifications@github.com>;  
  发送时间: 2018年5月14日(星期一) 中午1:48  
  收件人: "shimohq/chinese-programmer-wrong-pronunciation"<chinese-programmer-wrong-pronunciation@noreply.github.com>;  
  抄送: "Subscribed"<subscribed@noreply.github.com>;   
  主题: Re: [shimohq/chinese-programmer-wrong-pronunciation] 鸿鹄之志 (#199)  
   
   
   
   
  鸿浩之志
