### ISSUE TITLE
优化排版

### ISSUE THREAD

**Issue by wuyuanwei** [shimohq/chinese-programmer-wrong-pronunciation#20]
| 单词  | 正确发音 | 错误发音 |
| - | - | - |
| AJAX [🔊](http://dict.youdao.com/dictvoice?audio=AJAX&type=2) | ✅ ['eidʒæks] | ❌ [ə'dʒʌks] |

　　　　　　　　　　||
　　　　　　　　　　\\/

| 单词  | ✅ 正确发音 | ❌ 错误发音 |
| :-: | :-: | :-: |
| AJAX | [['eidʒæks]](http://dict.youdao.com/dictvoice?audio=AJAX&type=2) | [ə'dʒʌks] |

```
| 单词  | ✅ 正确发音 | ❌ 错误发音 |
| :-: | :-: | :-: |
| AJAX | [['eidʒæks]](http://dict.youdao.com/dictvoice?audio=AJAX&type=2) | [ə'dʒʌks] |
```

**Comment by enkows** [comment]
Pull request welcome
