### ISSUE TITLE
admin 这个肯定很多人读错！！！

### ISSUE THREAD

**Issue by yuuk** [shimohq/chinese-programmer-wrong-pronunciation#209]
正确：['ædmɪn]
错误：[ɜ:dmɪn]

**Comment by gajanlee** [comment]
哈哈，读['ædmɪn]别人都不知道你在说什么

**Comment by jnoodle** [comment]
https://github.com/jnoodle/common-programming-words-english-pronunciation

**Comment by dwing4g** [comment]
但 administrator 的音标是 [əd'mɪnɪstreɪtə], 为什么 admin 就发音为 ['ædmɪn] 呢

**Comment by wanming** [comment]
很有意思的讨论，但是如果一个词如果大家都读成错的，那 maybe 这个错的可以理解为是对的😄
