### ISSUE TITLE
关于为什么jpg是那个发音

### ISSUE THREAD

**Issue by edwinyzh** [shimohq/chinese-programmer-wrong-pronunciation#22]
建议加个备注：
因为`jpg`是`jpeg`的缩写，故而发` [ˈdʒeɪpɛɡ]`。

**Comment by wanming** [comment]
我直接改成 `jpeg` 吧?

**Comment by wanming** [comment]
https://github.com/shimohq/chinese-programmer-wrong-pronunciation/commit/103174986d2fd73d005cf609484992ed7de118a1 feel free to reopen
