### ISSUE TITLE
三个字母的一律按字母读

### ISSUE THREAD

**Issue by dvaknheo** [shimohq/chinese-programmer-wrong-pronunciation#224]
嗯，就是dos (dou-s),lua（lu-a） ,别扭了点
其他都很好用
git ,sql ,git 都这么来。
vue 也是 v u e 更好点

**Comment by menq** [comment]
Vue 文档有明确的说怎么读哦。

**Comment by Danorge** [comment]
git add Readme你要念g-i-t a-d-d read me吗？
