### ISSUE TITLE
access两种读法都可以

### ISSUE THREAD

**Issue by x1angli** [shimohq/chinese-programmer-wrong-pronunciation#226]
access （重音在第一音节）主要用于名词
access （重音在第二音节）主要用于动词

**Comment by ygmyth** [comment]
有些词是这样,但 access 名词和动词都一个音

**Comment by x1angli** [comment]
以前我听过老美同事读过access动词重音第二音节。
Well, 相比起其他词更明确的读音标准，这个词的读音更像是一种民间习惯，听的人明白就行了……

**Comment by vilicvane** [comment]
https://www.oed.com/dictionary/access_v2

确实是两种读法都可以。
