### ISSUE TITLE
Avatar 的重音

### ISSUE THREAD

**Issue by elepone** [shimohq/chinese-programmer-wrong-pronunciation#23]
Avatar 的重音标错了吧，应该是['ævətɑr]

**Comment by wanming** [comment]
前面有个重音, 标在了下面..

**Comment by elepone** [comment]
可是这个单词只有一个重音啊

**Comment by wanming** [comment]
https://github.com/shimohq/chinese-programmer-wrong-pronunciation/commit/7b30ee0db1830e55f1175a16b8294b9d07acf038 已修正, 谢谢.
