### ISSUE TITLE
要是能配上音频就太棒了～

### ISSUE THREAD

**Issue by iostyle** [shimohq/chinese-programmer-wrong-pronunciation#232]

**Comment by wanming** [comment]
readme 里暂时不支持，以后会考虑其他途径实现音频，感谢~

**Comment by jingjingxyk** [comment]
> 无页面跳转收听正确读音请安装我们的 [chromium 扩展](https://github.com/shimohq/chinese-programmer-wrong-pronunciation/blob/master/tools/chromium_extension/README.md)
