### ISSUE TITLE
axios 怎么念？

### ISSUE THREAD

**Issue by pcandlej** [shimohq/chinese-programmer-wrong-pronunciation#237]
axios 怎么念？知乎上看比较常用的叫『阿克休斯』，但是谷歌给的中文叫『爱克信』，日语听起来像『阿克西欧』，老外都怎么读呢？

**Comment by libook** [comment]
可以参考这个
https://github.com/axios/axios/issues/802

**Comment by noisnemid** [comment]
i personally prefer to read it as/ækzaios/, which sounds cool, although according to issue#802 it sounds /æksi:os/.
maybe that there's not an official pronounciation for the names of the new tech or terms is a cool thing, which let us know that the world is full with possibilities.
isn't it? :-)

**Comment by libook** [comment]
@noisnemid This English word is from Greek. So the pronunciation is not important any more.
 /ækzaiəus/ is truly cool. Maybe you can ask maintainers of Axios for thinking about it.

**Comment by ShisiJu** [comment]
https://www.howtopronounce.com/axios

**Comment by wanming** [comment]
https://www.youtube.com/watch?v=6LyagkoRWYA  这个视频里的发音可以参考下，类似「阿克休斯」
