### ISSUE TITLE
常用的 interesting 究竟怎么读？

### ISSUE THREAD

**Issue by edisonator** [shimohq/chinese-programmer-wrong-pronunciation#24]
中学英语的教读，是把中间的音节读作『tri』，类似白话读音『吹』

大学英语外教的教读，是把中间的音节分作两步连读『təˌre』，类似白话读音『特瑞』

**Comment by fghpdf** [comment]
https://translate.google.com/?source=gtx#en/zh-CN/interesting

应该是 tə

可以让谷歌发音一下

![image](https://cloud.githubusercontent.com/assets/7081582/23200539/cc72e8b4-f90f-11e6-9be1-734c97158ea4.png)

中学那个是英式发音

**Comment by wanming** [comment]
区别不大, 暂不收录

**Comment by yjfvictor** [comment]
> https://translate.google.com/?source=gtx#en/zh-CN/interesting
> 
> 应该是 tə
> 
> 可以让谷歌发音一下
> 
> ![image](https://cloud.githubusercontent.com/assets/7081582/23200539/cc72e8b4-f90f-11e6-9be1-734c97158ea4.png)
> 
> 中学那个是英式发音

自己看那个 ə 在括号里面，就是可有可无。这本来就是两种读音都行。
