### ISSUE TITLE
建议以美音为发音

### ISSUE THREAD

**Issue by arkninja** [shimohq/chinese-programmer-wrong-pronunciation#258]
互联网开发美国为重心，用英国口音发音的太少见了。
北欧的程序员现在说英语讨论开发时也是美音发音

**Comment by greensea** [comment]
反对，这对以英音为主的程序员不公平。
建议同时标注英音和美音。

**Comment by jjeejj** [comment]
同意，现在看音标都是看的美式音标

**Comment by wanming** [comment]
yuanchen 已经把美音加上了，请查阅 readme
