### ISSUE TITLE
建议删库，读音没有对错之分

### ISSUE THREAD

**Issue by pnck** [shimohq/chinese-programmer-wrong-pronunciation#259]

**Comment by LiarrDev** [comment]
为什么会有这么奇怪的观点…

打个比方，中文“人”这个字，普通话发音是 ren，你非要读成 zhu，这没有对错之分吗？

我认为可以接受读起来有口音，但不能够接受完全错误的读法，这影响了程序员之间的有效沟通，而这正是这个库的意义所在。

**Comment by gitGksgk** [comment]
但这个库更多的是 普通话发音 ren  错误发音 lin nin len  而不是zhu 这样的差别

**Comment by LiarrDev** [comment]
> 但这个库更多的是 普通话发音 ren 错误发音 lin nin len 而不是zhu 这样的差别

😐论普通话普及的重要性

**Comment by codeSu97** [comment]
这个主要还是为了有效保证协作的沟通效率吧

**Comment by giveahug** [comment]
那没必要普及普通话了

**Comment by chenboshuo** [comment]
我在想如果你不认同或者不喜欢不看就行了吧，这个没有强制性，还是很多人有兴趣了解怎么读，或者一开始设计怎么读， 然后还会引导一些人去看当时的原始文档去看开发者想怎么读，只是参考资料吧，如果有别的材料读音可以参考补充的。
