### ISSUE TITLE
没有读对所有的单词，还能加入石墨文档吗？/doge

### ISSUE THREAD

**Issue by greensea** [shimohq/chinese-programmer-wrong-pronunciation#267]
目前 README.md 中列出了差不多 80 个单词，即使是英语母语人士可能也无法读对所有的单词。
那么问题来了：
1. 是不是一定要完全读对所有的单词，才能通过底部的招聘链接投简历呢？
2. 如果不是，那么需要读对多少单词才能通过底部的招聘链接投简历呢？

**Comment by wanming** [comment]
哈哈只要合适，读不读对都 OK 的，欢迎投简历到 wanming#shimo.im
