### ISSUE TITLE
linux怎么读？

### ISSUE THREAD

**Issue by akaxiaok** [shimohq/chinese-programmer-wrong-pronunciation#27]

**Comment by loveisbug** [comment]
`[ 'lɪnəks ] [ 'lɪniks ]`

**Comment by fghpdf** [comment]
https://translate.google.com/?source=gtx#en/zh-CN/Linux

![image](https://cloud.githubusercontent.com/assets/7081582/23201102/e8ae4390-f912-11e6-9c47-a084130f201f.png)

**Comment by wanming** [comment]
已加.

**Comment by wsxy162** [comment]
然后外面放了个有道的不一样的读音……讽刺自己吗？
