### ISSUE TITLE
不加上 Kubernetes / K8s 吗？

### ISSUE THREAD

**Issue by gongzhang** [shimohq/chinese-programmer-wrong-pronunciation#270]
天天听 K、八、S 😂

**Comment by yuqingc** [comment]
/kuber'neitis/

**Comment by aizigao** [comment]
k8s 是 Kubernetes 的缩写没有问题，
类似的有 i18n Internationalization

**Comment by gongzhang** [comment]
我观点变了。我觉得每个人都可以自由地按自己喜欢的方式来读一个词，不应要求所有人都按所谓的“标准”来发音。特别的，对于 K、8、S 这个读法，它不会引起任何交流障碍，同时又比 kubernetes 容易发音。所以我直接关闭了。
