### ISSUE TITLE
不如来一手外国程序员容易发音错误的单词？

### ISSUE THREAD

**Issue by poozhu** [shimohq/chinese-programmer-wrong-pronunciation#276]
我承认单词正确发音可能有必要，但这种无聊的仓库也有11k star 就有点像个笑话了

**Comment by javascripet** [comment]
> 我承认单词正确发音可能有必要，但这种无聊的仓库也有11k star 就有点像个笑话了

自己不要脸和懒还要批判别人有追求
可笑

**Comment by poozhu** [comment]
> > 我承认单词正确发音可能有必要，但这种无聊的仓库也有11k star 就有点像个笑话了
> 
> 自己不要脸和懒还要批判别人求实
> 可笑

对于我来说，我明白自己需要什么，需要花时间在什么地方，并且自认为对这些单词的发音不会错到离谱，日常交流和工作不会存在问题，我没有花时间在研究读音上就就叫不要脸和懒？不如您先自己审视一下自己？

仓库挂着 chinese-programmer ，其他国家包括 us en 的程序员人人都确保的读音能达到标准或者在意自己是否标准吗？我等着看多久会出一个 us/en/India/russia 对应的仓库

语言作为一个工具，它的作用就是传递信息，方便交流，你又不是要研究英语或者跑去教授英语，非要去纠正这  [ɜ:d'mɪn] ->['ædmɪn] 的读音的必要性是什么？ 站在你面前读 [ɜ:d'mɪn] 你就听不懂了吗？或者读 [ɜ:d'mɪn] 的程序员水平就不行？

求实是正确的，但是有些时候要搞清楚是不是有比研究读音更重要的事情，比如了解更多技术细节，代码技巧，提升代码质量，提高开发效率等等。

并且我冒昧的问一句，11k star ，这 11k 里面的 chinese-programmer 你们普通话说的标准么，对你们的生活造成了什么巨大的影响？

**Comment by integzz** [comment]
> 
> 
> > 我承认单词正确发音可能有必要，但这种无聊的仓库也有11k star 就有点像个笑话了
> 
> 自己不要脸和懒还要批判别人求实
> 可笑

哥们儿，凡事有一说一，因为观点不同，对别人进行人身攻击不合适。

**Comment by MeloGuo** [comment]
对你没帮助，忽视就好了。何必进来特意提个 issue 来嘲笑一番呢？

**Comment by Attt** [comment]
你这好比跑人家里说你家装修我不喜欢，战狼是吧，特别闲的话可以咬打火机

**Comment by geeklihui** [comment]
为什么明知自己错了还不愿意改？就因为很多人读的都是错的？这不就是这个仓库的意义吗，更多人看到就能推动更多人使用正确的读音。
我不想再面对每次我发出  Linux、Nginx、MAC、SQL、NAS、Adobe 等正确读音时，对面的人一脸你个 SB 的表情了。

**Comment by poozhu** [comment]
> 为什么明知自己错了还不愿意改？就因为很多人读的都是错的？这不就是这个仓库的意义吗，更多人看到就能推动更多人使用正确的读音。 我不想再面对每次我发出 Linux、Nginx、MAC、SQL、NAS、Adobe 等正确读音时，对面的人一脸你个 SB 的表情了。

我两年前已经在上面有过回复了，难以理解的话给你总结一下
1. 没有人说过发音错了不愿意改
2. 单词正确发音可能有必要，但单词发音一定不是写代码需要重点关注的内容
3. 语言的作用是传递信息，你不是在参加演讲比赛
4. 期望在 Trending 上发现中文相关仓库时，是关于框架&实际代码相关，而不是讨论发音&买房&长寿&做饭...这些是这个平台或者说国内程序员主要研究的内容吗？

**Comment by poozhu** [comment]
> 你这好比跑人家里说你家装修我不喜欢，战狼是吧，特别闲的话可以咬打火机

抱歉，不是每个人都和你一样有咬打火机这种爱好，你喜欢的话可以自己在家咬。提 issue 的原因我在上面已经解释过了，看不懂的话可以补一下小学语文。
