### ISSUE TITLE
Incorrect phonemes for Grafana and Kubernetes

### ISSUE THREAD

**Issue by b1f6c1c4** [shimohq/chinese-programmer-wrong-pronunciation#297]
I hear /gɹə ˈfɑːn ˌɑː/ [ɡʷɹ̠ʷə ˈfɑ̃ːn ˌɑː] and /ˈkuːb ə˞ ˌnet iz/ [ˈkʰʊu̯b ɹ̠̩ ˌnɛɾ iːz] for the two words. Try compare:

- Grafana v.s. Tatjana
- Kubernetes v.s. diabetes v.s. treaties

Also see https://github.com/b1f6c1c4/programming-pronunciations-en_US/commit/7ebcb599f4cebd581a762850fe3a70e75ade188c

**Comment by yuanchen8911** [comment]
> I hear /gɹə ˈfɑːn ˌɑː/ [ɡʷɹ̠ʷə ˈfɑ̃ːn ˌɑː] and /ˈkuːb ə˞ ˌnet iz/ [ˈkʰʊu̯b ɹ̠̩ ˌnɛɾ iːz] for the two words. Try compare:
> 
> 
> 
> - Grafana v.s. Tatjana
> 
> - Kubernetes v.s. diabetes v.s. treaties
> 
> 
> 
> Also see https://github.com/b1f6c1c4/programming-pronunciations-en_US/commit/7ebcb599f4cebd581a762850fe3a70e75ade188c

Kubernetes is a Greek word. Not sure Grafana is even a word. Both are project names. I doubt they have "standard" pronunciations. Can you submit a PR on correct phonetic transcriptions? Thanks. 

https://www.geekwire.com/2016/ever-come-kooky-kubernetes-name-heptio/

https://community.grafana.com/t/how-to-pronounce-grafana/1393

**Comment by b1f6c1c4** [comment]
I got the phonemes directly from the two sources you linked following [the rules for English pronunciation respelling](https://en.wikipedia.org/wiki/Pronunciation_respelling_for_English).

@iorioikawa Could you please confirm the phonemes and submit a PR to this repo?

**Comment by IoriOikawa** [comment]
Pronunciation checked & verified. Will do.
