### ISSUE TITLE
点击打开新页面体验不太好

### ISSUE THREAD

**Issue by orangle** [shimohq/chinese-programmer-wrong-pronunciation#313]
有啥办法能在当前页面听发音吗

**Comment by wwwenjie** [comment]
https://cpwp.netlify.app/

**Comment by yuanchen8911** [comment]
> https://cpwp.netlify.app/
非常好！你这个单词list和github的同步吗？我把网址加到首页去。谢谢

**Comment by wwwenjie** [comment]
这个不是我做的，是@antfu7的项目，有同步的。不过已经在 readme 中了。

**Comment by orangle** [comment]
帅

**Comment by jingjingxyk** [comment]
> 无页面跳转收听正确读音请安装我们的 [chromium 扩展](https://github.com/shimohq/chinese-programmer-wrong-pronunciation/blob/master/tools/chromium_extension/README.md)
