### ISSUE TITLE
建议添加 Github Dicussions

### ISSUE THREAD

**Issue by wwwenjie** [shimohq/chinese-programmer-wrong-pronunciation#326]
Issues 中有大量关于添加某个单词的讨论，如果将他们放置在 Github Dicussions 会不会更好？
Dicussions 介绍：https://docs.github.com/en/discussions

**Comment by Hootrix** [comment]
> Issues 中有大量关于添加某个单词的讨论，如果将他们放置在 Github Dicussions 会不会更好？
> Dicussions 介绍：https://docs.github.com/en/discussions

附议

**Comment by gaoryrt** [comment]
附议

**Comment by wanming** [comment]
已开
