### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by wizarot** [shimohq/chinese-programmer-wrong-pronunciation#36]
Python 这个就没几个读对发音的

**Comment by hkongm** [comment]
求错误的音标。。。

我身边没有听过发错的啊

**Comment by wizarot** [comment]
Python  派森  派风 什么的, 都是错误发音.
麻烦大家去外国人的Python课上好好听听. 这个音到底怎么发的啊....

**Comment by lisnb** [comment]
Python（英国发音：/ˈpaɪθən/ 美国发音：/ˈpaɪθɑːn/） 至少wikipedia上是这么写的。https://zh.wikipedia.org/wiki/Python 
我就读前面那个，like 派森 but not really the same, 我也发现我在读前面那个发音时，一些人带着“你是不是说错了亲“的眼神看我。我觉得这两个都好吧，只要th发Θ就没什么吧

**Comment by wanming** [comment]
肯定是因为你读 Θ 的时候咬舌了哈哈

**Comment by wizarot** [comment]
哎,问题就是这个 th发Θ 的音.  不是s  而是大概上下齿咬舌头发出的那个破擦音, 我觉着有点类似于 松的发音,不过发音时候要咬舌头.

**Comment by lisnb** [comment]
@wanming  不就是要咬舌么...

**Comment by lisnb** [comment]
我觉得从音标上来看，如果是按照 /ən/来读，就和‘森’差不多，按照/ɑːn/来读就和'桑'差不多，这两个是维基百科的音标，其他地方也有标成 /ɔn/的，那就类似'松'，不过我还是觉得只要th发对了就都还好吧...

**Comment by lilydjwg** [comment]
我也没怎么听过错误的发音呢。
