### ISSUE TITLE
公然与“文化自信”唱反调，居心何在？！

### ISSUE THREAD

**Issue by sharljimhtsin** [shimohq/chinese-programmer-wrong-pronunciation#361]
pinyin is the best.

**Comment by Flora945** [comment]
Alibaba Huawei怎么读可以自信, 别人创造的东西你自己非要安个别的名字, 那就是自大

**Comment by shikingram** [comment]
> pinyin is the best.

need touxiang hao sao a~ wo hao xi huan.
