### ISSUE TITLE
current & attribute

### ISSUE THREAD

**Issue by hkongm** [shimohq/chinese-programmer-wrong-pronunciation#37]
current
英 [ˈkʌrənt]  美 [ˈkɜrənt] 

attribute
英 [əˈtrɪbju:t]  美 [əˈtrɪbjut]

**Comment by hkongm** [comment]
edition
英 [ɪˈdɪʃn]  美 [ɪˈdɪʃən] 
错误的 [eˈdɪʃn]

**Comment by lisnb** [comment]
attribute 在 http://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD/attribute 这里是 UK ​ /ˈæt.rɪ.bjuːt/  US ​ /ˈæt.rɪ.bjuːt/

**Comment by Dafrok** [comment]
这俩词没有什么异议吧。。。

**Comment by lilydjwg** [comment]
一堆常用词我都觉得毫无异议的说……

**Comment by wanming** [comment]
读错的不多, 先关闭了

**Comment by yjfvictor** [comment]
attribute
动词   BrE /əˈtrɪbjuːt/ ; NAmE /əˈtrɪbjuːt/
名词   BrE /ˈætrɪbjuːt/ ; NAmE /ˈætrɪbjuːt/
