### ISSUE TITLE
建议添加：C#

### ISSUE THREAD

**Issue by Surbowl** [shimohq/chinese-programmer-wrong-pronunciation#379]
C# 由于形似 "C 井"，常被国人误念为 /si jing/
实际上，C# 的全称为 C Sharp，正确念法为英音 /si ʃɑːp/，美音 /si ʃɑːrp/

C# 名字的灵感源自乐谱中的升音符 Sharp，在乐谱中写作 #，代表此音符要在音高上升半级，同时 # 符号的形状像由四个加号组成，进一步说明了 C# 对 C++ 的继承与发扬

[官方发音视频](https://www.youtube.com/watch?v=BM4CHBmAPh4&list=PLdo4fOcmZ0oVxKLQCHpiUWun7vlJJvUiN)
[创始人采访](https://www.red-gate.com/simple-talk/opinion/geek-of-the-week/anders-hejlsberg-geek-of-the-week/)
[维基百科-C Sharp](https://en.wikipedia.org/wiki/C_Sharp_(programming_language)#Language_name)

**Comment by yuanchen8911** [comment]
可以提个PR吗？谢谢
