### ISSUE TITLE
请把这几个单词也加上,整天听各种奇怪发音快疯了

### ISSUE THREAD

**Issue by wizarot** [shimohq/chinese-programmer-wrong-pronunciation#38]
Symfony
Laravel
Repository
Orical
PhpStorm
github
i18n
Entity
bower
git merge
git commit
Vue
module
docker
arduino
Adobe
Chrome
JAVA
Ubuntu
Linux
暂时想到,整体被人念错的就这些了.  整天听这些奇怪读音会疯的啊!

**Comment by wizarot** [comment]
麻烦看到的朋友改过来....

**Comment by AsiamCn** [comment]
github 莫非读 “吉特哈不” :laughing:

**Comment by wanming** [comment]
有点多, 方便提个 PR 吗 :)

**Comment by zhyma** [comment]
每认识一个程序员就会学到Azure的一种新读法

**Comment by zoffyzhang** [comment]
i18n pronounce international?

**Comment by LovingYoung** [comment]
@zoffyzhang I think "i18n" is abbreviation of "internationalization". There are 18 characters between the first character 'i' and the last character 'n'.

**Comment by CallMeZhou** [comment]
@zhyma Azure和Agail不是念“阿朱”和“阿娇”吗？

**Comment by wanming** [comment]
这几个词有几个不合适, 有几个已经加了, 谢谢建议

**Comment by hkongm** [comment]
爱轴
