### ISSUE TITLE
babel 两种发音

### ISSUE THREAD

**Issue by saccohuo** [shimohq/chinese-programmer-wrong-pronunciation#46]
babel按照韦氏音标或者欧路来看都有两种发音。具体选哪个应该按照美国人实际使用情况，不能盲信有道音标和有道自带的读音吧。

 KK 音标：/ˈbebəl/  第一个元音发音跟中文的“北”应该是一致的。美式。
韦氏音标：\ˈbā-bəl, ˈba-\ 两种发音都有。第一个元音可以发音“北”或者“巴”。美式。
DJ音标：/ˈbeibəl/ 第一个元音发音为“北”。英式。

**Comment by wanming** [comment]
考虑到两种读音均可, babel 删了吧
