### ISSUE TITLE
请统一音标标准和发音标准，最好可以参考美国人实际发音

### ISSUE THREAD

**Issue by saccohuo** [shimohq/chinese-programmer-wrong-pronunciation#47]
看到词里面有混淆音标的情况，所以最好统一音标标准。比如都使用KK音标，美式的，虽然美国人可能更多地使用韦氏音标。有道的音标区分不够明显，发音方面跟音标也不完全对照。

发音方面感觉使用韦氏的发音更有说服力吧，有道的不敢全信。

**Comment by wanming** [comment]
有相关的网站没? 对这方面不是太了解

**Comment by saccohuo** [comment]
下面是几个参考，可信度未作深究。
[音标体系详解](http://topget.org/xxs/viewknow.php?knowid=2016050317202270982809)
[美国人用的是国际音标还是KK音标?_音标教学资料](http://en-yinbiao.xiao84.com/2015/24245.html)
[十分钟明白IPA,DJ,KK等音标_英语杂谈_天涯论坛](http://bbs.tianya.cn/post-english-172803-1.shtml)
[為什麼美國人不喜歡用國際音標注音? - 北大中文论坛 www.pkucn.com - Powered by Discuz!](http://www.pkucn.com/viewthread.php?action=printable&tid=230098)

**Comment by wanming** [comment]
想了一下还是以最常用的音标为准吧, 因为大部分人没有你辣么专业的, 为了便于阅读避免选择困难症, 我考虑了下还是只写最常听到的, 或者是最容易查到的. 后续可能会加上英文音标和美国音标的区分. 感谢提出建议, feel free to reopen.

**Comment by saccohuo** [comment]
是的，但是常用的英式是DJ音标，常用的美式是KK音标。而我看表格里面是混用的，这样就很难对比。建议正确和错误的音标标注全部使用KK音标。

**Comment by wanming** [comment]
研究了下大部分人可能看了 KK 会有点困惑, 因为大部分人高中大学接触的都是 DJ , 用 DJ 音标标注美式发音你觉得怎么样..

**Comment by saccohuo** [comment]
哈哈，我小时候学的也是DJ的，但是要明白，小时候学的是英式英语。
DJ常用来标注英音，但标注美音也是可以的。

但是有个很重要的点：现在的有道、欧路等词典都是使用DJ音标标注英音，使用KK音标标注美音。要想在repo里面写出DJ音标标注的美音则需要自己靠感觉转换，或者另外找一个其他词典。

所以，即使我们学的是DJ，我还是觉得标注的美音音标不要跟有道等主流词典有出入。

**Comment by wanming** [comment]
我也发现了.. 还是用 DJ 了, 捂脸

**Comment by saccohuo** [comment]
为什么还是打算用DJ呢，不知道是不是方便让我知道一下原因。
真的用DJ的话，需要找个比较权威的使用DJ标注美式发音的词典，作为大家的参考。

**Comment by wanming** [comment]
DJ 标注美式发音的情况比较少见, 尽量用英式发音. e 这种在英式里对应 ei ,不懂美式的人可能会念错.

**Comment by saccohuo** [comment]
所以意思是打算直接使用英式发音？

**Comment by wanming** [comment]
是的

**Comment by wanming** [comment]
请教下, DJ 音标里, i 后面是必跟 : 的吗? 看了下有 i: 和 ɪ 这两种音

**Comment by saccohuo** [comment]
DJ音标里面长元音i:，短元音ɪ。所以i后面一定是跟:的。

**Comment by saccohuo** [comment]
话说为什么打算使用英音呢？
个人感觉现在主流思想应该是向掌握核心科技的美帝靠拢，而不是向当初的日不落帝国看齐哎。

**Comment by fghpdf** [comment]
也说了只是个人基本关注

比如我还是很喜欢英音，没有必要强迫把别人的习惯转成这样

掌握核心科技的主流思想应该是多样性共存，而不是仅能发美音

简单的说，求同存异

**Comment by saccohuo** [comment]
哈哈，确实是这样，所以那只是我个人看法，看大家意见吧。不过两种都放上去，应该能够兼顾我们这两种不同的习惯吧。

**Comment by fghpdf** [comment]
@saccohuo 我也同意，哈哈，为不同👏

**Comment by wanming** [comment]
https://github.com/shimohq/chinese-programmer-wrong-pronunciation/pull/71/files 麻烦看一下

**Comment by saccohuo** [comment]
@wanming 我看了一下海词，还不错，但我也不是专业的，所以只是我的个人感觉。暂时可以先用英音和DJ来标注吧。后续还是希望可以考虑一下增加美音及其音标，美音音标的具体形式可以再定。

**Comment by wanming** [comment]
好的
