### ISSUE TITLE
content 两种发音，后者也是对的，两种发音的意思不同

### ISSUE THREAD

**Issue by VectorLu** [shimohq/chinese-programmer-wrong-pronunciation#49]
content 1 |ˈkɒntent|
A.nounUncountable
①(relative quantity)含量 hánliàng
the fat/vitamin content
脂肪/维生素含量
to have a low/high lead content
铅含量低/高
②(meaning)内容 nèiróng
debates about form and content
有关形式与内容的争论
③(subject matter)主题 zhǔtí
④(of web site)网站内容 wǎngzhàn nèiróng
B.contents noun plural
①(of jar, bag)容纳的东西 róngnà de dōngxi
she sold the flat and its contents
她把公寓和里面的东西都卖了
②(of book, magazine)
(list or table of) contents
目录mùlù
③(subject matter of book etc.)内容 nèiróng
content 2 |kənˈtent|
A.adjective
①(satisfied)满意的 mǎnyì de (willing)愿意的 yuànyì de
to be content with [something]
对某事物满意
to be content to do [something]
愿意做某事
not content with doing ...
不愿意做…
②(peacefully happy)心满意足的 xīn mǎn yì zú de
B.transitive verb
(please)使满意 shǐ mǎnyì
to content [somebody] with [something]
用某事物来满足某人
to be easily contented
容易满足
C.reflexive verb
to content oneself
满足mǎnzú
to content oneself with [something]
使自己满足于某事物shǐ zìjǐ mǎnzú yú mǒu shìwù
D.noun
Uncountable满足 mǎnzú
a feeling of content
满足感

**Comment by wanming** [comment]
谢谢指正.
