### ISSUE TITLE
*sudo* 的发音也特别迷，我一直没有 GET 正确的念法。

### ISSUE THREAD

**Issue by Dafrok** [shimohq/chinese-programmer-wrong-pronunciation#5]
> 参考：https://arstechnica.com/civis/viewtopic.php?t=120828

**Comment by wanming** [comment]
看起来 `[suːdoʊ]` 和 `[su:du:]` 是最常读的

**Comment by Dafrok** [comment]
我们公司很多人读 `[sudɒ]`

**Comment by fanweiya** [comment]
应该是读[su:du:]
[参考FORVO英音](https://zh.forvo.com/search/sudo/en/)

**Comment by limichange** [comment]
https://arstechnica.com/civis/viewtopic.php?t=120828

老外也很迷惑:D

**Comment by wanming** [comment]
先用 [su:'du:] 吧
