### ISSUE TITLE
hover的发音有点疑问

### ISSUE THREAD

**Issue by takashiki** [shimohq/chinese-programmer-wrong-pronunciation#50]
这是 mac 自带词典的结果：
![https://ww4.sinaimg.cn/large/006tNbRwgy1fcziinolv1j30ae0b70tp.jpg](https://ww4.sinaimg.cn/large/006tNbRwgy1fcziinolv1j30ae0b70tp.jpg)

**Comment by wanming** [comment]
已修正, 谢谢
