### ISSUE TITLE
mock 读作 /mäk/

### ISSUE THREAD

**Issue by lexrus** [shimohq/chinese-programmer-wrong-pronunciation#52]
以前我一直读错成某客，直到听了罩超的直播。

**Comment by wanming** [comment]
ä 这种音标不了解, 能否提供大家初高中学习的那种音标?

**Comment by lexrus** [comment]
抱歉，小时候音标没学好，不知道有什么标准可参考么？我这个是在 macOS 自带的 Dictionary 里查出来的。

![screen shot 2017-02-23 at 9 43 51 am](https://cloud.githubusercontent.com/assets/219689/23241179/9e37ef38-f9ac-11e6-9bef-3cc763cbdb7c.png)

**Comment by soakit** [comment]
![image](https://cloud.githubusercontent.com/assets/11240668/23254120/e7938120-f9f1-11e6-8149-340a72e0a8c9.png)

**Comment by wanming** [comment]
ä 是美式的韦式音标, 我们采用的是英式的, 两个都没问题
