### ISSUE TITLE
想用此仓库的资源做一个小巧的免费的没有广告的 App，不知道仓主同意不？

### ISSUE THREAD

**Issue by lexrus** [shimohq/chinese-programmer-wrong-pronunciation#53]
如题。

**Comment by enkows** [comment]
非常欢迎, 注明数据来源即可.

**Comment by lexrus** [comment]
已完成：
https://github.com/lexrus/Huahui

**Comment by lilydjwg** [comment]
San José 好像解析出错了呢。

PS: 要不要做个 Duolingo flashcards 样式的程序？就是每次出一张卡片，写上单词，练习者读完之后翻卡片查看正确读音，并且告诉程序读对了没。

**Comment by lexrus** [comment]
@lilydjwg 谢谢，已修正。

你这个提议很好，但我没时间搞，抱歉。
