### ISSUE TITLE
没必要列出错误的发音

### ISSUE THREAD

**Issue by ansel333** [shimohq/chinese-programmer-wrong-pronunciation#70]
多看一次就是多接受一次错误印象

**Comment by saccohuo** [comment]
个人觉得还是有必要列出来，至少在同行发错音的时候知道他指的是什么，而不是一脸懵逼，降低交流效率

**Comment by fghpdf** [comment]
有人读的是英式发音，不是我们讨论的范畴，只是让读错的人确认一下，他到底是读错了，还是英式发音。所以，我推荐增加英式发音~~

**Comment by lgh06** [comment]
我也建议把错误发音这列更换成英音…… 错的读音有千千万万种…… 没必要替错误读音做宣传……

**Comment by lilydjwg** [comment]
不建议列出错误读音+1。

> 至少在同行发错音的时候知道他指的是什么

你列得又不全。比如你能一下子听明白 [ˈgəʊˌes] 是什么鬼吗？

另外对于非词典词给出来源。比如 deque 那个，在维基百科上还处于 `[citation needed]` 状态呢。

**Comment by Batur24** [comment]
我的意见是列出来，看到那些错误的发音，也是一件有意思的事情。:-)

在 2017年2月23日 下午2:16，依云 <notifications@github.com>写道：

**Comment by lilydjwg** [comment]
要不默认隐藏也行。毕竟不是母语使用者，错误的见多了容易弄不清到底哪个是对的哪个是错的。

**Comment by ycwei982** [comment]
加英式我今天抽个时间pr

**Comment by lilydjwg** [comment]
我做了一个只有正确发音的版本，并且去掉了容易读的常见词： https://github.com/lilydjwg/chinese-programmers-corrent-pronunciations-handbook
