### ISSUE TITLE
GUI读音纠错

### ISSUE THREAD

**Issue by 5cr1pt** [shimohq/chinese-programmer-wrong-pronunciation#82]
GUI |dʒiːjuːˈʌɪ|
abbreviation *Computing*
graphical user interface.

**Comment by lilydjwg** [comment]
[ˈʌɪ]? 不应该是 [ˈaɪ] 么？

读 /ɡuːiː/ 是没有问题的（来源：英文维基百科）。

**Comment by x-ji** [comment]
是可以读 G-U-I, 但是一般都读 "gooi"

**Comment by 5cr1pt** [comment]
不好意思又查了下，Oxford Dictionary of English 上是标的 /dʒiːjuːˈʌɪ/，英文wiki上标的是 /ɡuːiː/ ，看了下 youtube 上老外也是读 /ɡuːiː/ ，是我搞错了。

**Comment by yjfvictor** [comment]
https://www.oxfordlearnersdictionaries.com/definition/english/gui
