### ISSUE TITLE
safari 的读音

### ISSUE THREAD

**Issue by lfzyx** [shimohq/chinese-programmer-wrong-pronunciation#86]
可以在 mac 上打开终端输入 `say safari` ，个人认为这个发音才是正确

**Comment by wanming** [comment]
有资料可以说明 mac 上的 speech 发音是标准的英式或者美式发音吗

**Comment by lfzyx** [comment]
输入命令 ：` say -v ?|grep English `，可以看到以下结果：

Daniel              en_GB    # Hello, my name is Daniel. I am a British-English voice.
Fiona               en-scotland # Hello, my name is Fiona. I am a Scottish-English voice.
Karen               en_AU    # Hello, my name is Karen. I am an Australian-English voice.
Moira               en_IE    # Hello, my name is Moira. I am an Irish-English voice.
Samantha            en_US    # Hello, my name is Samantha. I am an American-English voice.
Tessa               en_ZA    # Hello, my name is Tessa. I am a South African-English voice.
Veena               en_IN    # Hello, my name is Veena. I am an Indian-English voice.


其中，Daniel 是 British-English voice，Samantha 是 American-English ，

`say -v Daniel safari`听英式， `say -v Samantha safari`听美式

**Comment by lilydjwg** [comment]
那个发音是什么样的呀？

**Comment by lfzyx** [comment]
[safari.aiff.zip](https://github.com/shimohq/chinese-programmer-wrong-pronunciation/files/800967/safari.aiff.zip)

音频文件

**Comment by lilydjwg** [comment]
@lfzyx 这个跟仓库里标记的读音是一样的呀。

**Comment by yjfvictor** [comment]
“野生动物园”这个单词你们不认识吗？

https://dictionary.cambridge.org/dictionary/english/safari-park
