### ISSUE TITLE
增加static

### ISSUE THREAD

**Issue by dbw9580** [shimohq/chinese-programmer-wrong-pronunciation#87]
曾经我也读错为/'steitik/，这个词在各种语言里出现很多。

**Comment by DanteAndroid** [comment]
正确读音是 `[ˈstætɪk]` ，你发 /'steitik/ 实际上差别不大，一般很难分清 ei 和 æ，除非你发的特别标准

**Comment by lilydjwg** [comment]
@DanteAndroid  我觉得 /eɪ/ 和 /æ/ 区别挺大的呀，前者中文里有，后者普通话里是没有的。/æ/ 和 /e/ 以及 /ɛ/ 差别不太大。

**Comment by DanteAndroid** [comment]
/eɪ/ 比 /e/ 发音稍微长了点，但是这个库只是收集一些明显的、英语小白都能听得出区别的发音，讨论这个问题没必要

**Comment by lilydjwg** [comment]
@DanteAndroid 我的意思就是说 /eɪ/ 和 /æ/ 的区别对普通中国人已经很明显了啊。如果真要说「差别不大」，那应该是这两个音在某些地区是同音位的？

以及，我没讨论 /eɪ/ 和 /e/ 的差别。

**Comment by dbw9580** [comment]
这么说，null和now几乎都没区别。
最终的裁量还是留给Owner吧。

**Comment by wanming** [comment]
读错的不多, 先关闭了
