### ISSUE TITLE
权威一点的参考出处？

### ISSUE THREAD

**Issue by ylxdzsw** [shimohq/chinese-programmer-wrong-pronunciation#9]
像GUI，我不认为拆开念是多大的错误，能否使用权威的资料说明一下为什么每个单词只有第一个发音是正确的？

**Comment by wanming** [comment]
拆开念肯定不是错误, 有时候拆开念反而更好懂一点, 这点上看, `标题` 有点标题党~ 这个 `repo` "正确的发音" 只是拿了一个最经常被读的音标, 妄图建立一个程序员界的规范~ [捂脸]

**Comment by myst729** [comment]
对于英文缩略语，写法和读法都是有特定规则的。比较常见缩略语的有以下三类：

1. 截断缩略词
    对于较长的多音节单词，有时候为了省事，读和写会只取开头一两个音节。最常见，也是误读最严重的，毫无疑问是application的截断缩略词——**app**。正确的读法，应该和其在完整单词中的读法一致，**[æp]**，而不是滥大街的['eɪ'pi:'pi:]。此外，这不是首字母缩略语，因此全大写的APP也是错误的写法。这类缩略语也有例外，比如上面提到的repo，本身就是一个存在的单词，读作['rɪpoʊ]，因此repository的截断缩略词repo也借用这个读法，而不是在repository里的读法。也有一些源于网络的奇葩截断词，比如……imbalance截成imba，这已经完全破坏了原本的音节结构，属于错误的做法，然而存在即合理，whatever……

2. 首字母缩略词
   **首字母缩略**的概念就不多解释了，直接说**词**和**语**的区别。有些短语在首字母缩略以后，仍然可以依照音节构造的规则，像单词一样**读**出来。如NATO（北大西洋公约组织），读作 ['neɪtoʊ]；FIFA（国际足联），['fi:fə]。

3. 首字母缩略语
    还有一些缩略语，没法构造出能像单词一样易读的音节，比如UTF、GBK、XML，这类的读法就是挨个读字母的发音。

**Comment by myst729** [comment]
最后回到issue本身的问题，GUI是一个首字母缩略**词**，应该读作['ɡui]。

**Comment by ylxdzsw** [comment]
不不，Issue本身的问题并不是GUI怎么读，而是希望给每个单词的读法都给出一个相对权威的出处，而非zhihu, v2ex

**Comment by myst729** [comment]
#issuecomment-281556855 已经给出了常见几种类型的规则。

**Comment by ylxdzsw** [comment]
我大致看了一下这几种常见类型只能解释不到30%的词语，如果可以的话希望其它的也能添加权威出处

**Comment by ylxdzsw** [comment]
有明确出处的词语比如Linux, LaTeX, MySQL之类的，可以附上作者链接；英文的单词可以附词典链接，实在没有的wiki也行。现在参考资料就zhihu, v2ex，很难让人信服
