### ISSUE TITLE
标注的音标是英式 DJ 音标, 发音链接是美式 KK 音标 ？

### ISSUE THREAD

**Issue by zhulongcheng** [shimohq/chinese-programmer-wrong-pronunciation#93]
标注的音标是 `英式 DJ 音标`, 但是发音链接是 `美式 KK 音标`。
例如 retina ['retɪnə] http://dict.youdao.com/dictvoice?audio=retina&type=2
应该是 http://dict.youdao.com/dictvoice?audio=retina&type=1

**Comment by ycwei982** [comment]
我开了个PR #91 但是这一改别人的PR就废了

**Comment by ycwei982** [comment]
我的想法是再PR几个已有的PR+修复有道英式语音 工作量可能大（说不定他们就将错就错 然后把我的Fix PR Close 然后我的就废了）

**Comment by lexrus** [comment]
我建议找个 API，写个脚本，从原单词自动生成两种音标同时列出，那样会比人肉维护要方便一些。

**Comment by ycwei982** [comment]
要不音标+语音都用[有道api](http://fanyi.youdao.com/openapi?path=data-mode)？现在repo用的是dict.cn。

**Comment by wanming** [comment]
https://github.com/shimohq/chinese-programmer-wrong-pronunciation/commit/0920d889b7ccbf00bc220551291ec7ae04bd434f 谢谢指出
